services:
  users:
    # extends:
    #   file: users/docker/docker-compose.yaml
    #   service: users
    build:
      dockerfile: docker/Dockerfile
      context: users
    networks:
      - app-network
    volumes:
      - ./users/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure
  nginx:
    build:
      context: nginx
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    expose:
      - "443"
      - "80"
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - users
      - user-game-stats
      - livechat

  user-game-stats:
    build:
      dockerfile: docker/Dockerfile
      context: user-game-stats
    volumes:
      - ./user-game-stats/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "8080:8080"
    networks:
      - app-network
  livechat:
    build:
      dockerfile: livechat/docker/Dockerfile
    volumes:
      - ./livechat/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "9000:9000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
