services:
  users:
    build:
      dockerfile: users/docker/Dockerfile
    volumes:
      - ./users/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    networks:
      - app-network

  user_game_stats:
    build:
      dockerfile: user_game_stats/docker/Dockerfile
    volumes:
      - ./user_game_stats/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "8080:8080"
    networks:
      - app-network

  livechat:
    build:
      dockerfile: livechat/docker/Dockerfile
    volumes:
      - ./livechat/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
