services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf        # Main nginx config
      - ./nginx/conf.d:/etc/nginx/conf.d               # Server config in conf.d
      - ./frontend:/usr/share/nginx/html               # Frontend files
    depends_on:
      - users
      - user-game-stats
      - livechat
    networks:
      - app-network

  users:
    build:
      dockerfile: users/docker/Dockerfile
    volumes:
      - ./users/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

  user-game-stats:
    build:
      dockerfile: user-game-stats/docker/Dockerfile
    volumes:
      - ./user-game-stats/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:8080

  livechat:
    build:
      dockerfile: livechat/docker/Dockerfile
    volumes:
      - ./livechat/srcs/db.sqlite3:/app/db.sqlite3
    ports:
      - "9000:9000"
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:9000

networks:
  app-network:
    driver: bridge
