# Generated by Django 5.0.6 on 2024-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
