# Generated by Django 5.0.6 on 2024-09-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_user_alter_chatmessage_options_remove_chatroom_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedUsers',
            new_name='BlockedUser',
        ),
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
