# Generated by Django 5.0.6 on 2024-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_rename_blockedusers_blockeduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
