# Generated by Django 5.0.4 on 2024-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailTokenVerification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emailTokenVerificationExpiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
