# Generated by Django 5.0.6 on 2024-09-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='avatarImg',
            field=models.ImageField(blank=True, default='images/defaultAvatar.jpg', upload_to='images/'),
        ),
    ]
