# Generated by Django 5.0.6 on 2024-07-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
