# Generated by Django 5.0.6 on 2024-07-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_chatmessage_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
